### PR TITLE
Modify chose_manga to show list and select by manga ID

### PR DESCRIPTION
**Pull request by Alig1493**
@christianfds this is my iteration to display list and chose manga to download by ID.
#10

### CODE REVIEW

**Comment by christianfds** [comment]
Nice one @Alig1493. I believe we can improve it a bit.
What if instead of having the id used by the provider we use a number? It might make it easier for the user to choose the right manga. And I believe we can add a space between each manga just to make  it easier to read. Since we are changing the id to a number it would be nice to make explicit that this is the id.

I think we can also change the text to something like "Type the desired manga id or C to continue"

**Comment by Alig1493** [comment]
yeah we can use either index id of the manga in the list selection or the id either one works.

**Comment by Alig1493** [comment]
@christianfds see if the latest changes suffices or do you want it by numbers instead of id's.

**Comment by christianfds** [comment]
@Alig1493 I still think  it would make more sense to have numbers, we never know if a new provider might have some enormous ids. Maybe it can be done by passing a prefix to the manga.show()

**Comment by Alig1493** [comment]
@christianfds done

**Comment by christianfds** [comment]
@Alig1493 I found a couple issues.

The first one doesn't have its id shown. And if i select the id 1 it actually is selecting the one that should have id 0.
image

**Comment by Alig1493** [comment]
I see the problem. Also for display purposes I feel it's better to start from 1 instead of 0 so the entry to be selected will start from 1 and so forth.

**Comment by christianfds** [comment]
I'm sorry @Alig1493 , the original assignee of the issue submitted his PR, i didn't notice before this was a PR with another person assigned.

**Pull request closed without merging**
