### PR TITLE
Add dockerfile configuration and instructions of use

### LINKED ISSUE #4: Add a Dockerfile
Add a Dockerfile to allow the code to run without the need to have python or to need to install its dependencies.

The README.md should also be updated to included commands to build and the volume needed to export the files.

### PR DESCRIPTION
**Pull request by rodgeraraujo**
Added docker configuration to run the application. fixes #4 

ps: kindly evaluate and please tag the labels for `hacktoberfest`, thank u :P

### CODE REVIEW

**Comment by christianfds** [comment]
Hey @rodgeraraujo nice work here.

pre-commit found some small details to be fixed and i had some trouble running through the docker-compose, can you take a look at it?

image

**Comment by rodgeraraujo** [comment]
> 

@christianfds  how you run the compose, following the instructions in the README? Seems you don't have permissions to the directory.


https://user-images.githubusercontent.com/20842252/195617611-347bb45f-30c1-4705-bdf8-74379798c615.mp4

**Comment by christianfds** [comment]
Sorry for taking some time to answer @rodgeraraujo.
Yes i ran exactly as expected.

image
As you can see the user inside the container can't do anything. I belive it works for you because the UID e GID used are both the same of the user in your machine

**Comment by rodgeraraujo** [comment]
> Sorry for taking some time to answer @rodgeraraujo. Yes i ran exactly as expected.
> 
> image As you can see the user inside the container can't do anything. I belive it works for you because the UID e GID used are both the same of the user in your machine

I will try to check this.

**Comment by rodgeraraujo** [comment]
Can you try test again @christianfds? I remove the non root user from the Dockerfile

**Comment by christianfds** [comment]
Nice, now its running as expected, thank you

**Review by christianfds — APPROVED** [review]

**Pull request merged**
