### PR TITLE
Fixing blank issue problem

### PR DESCRIPTION
**Pull request by Karthik-PM**
seems like when i cloned the project again i had the same issue so i am creating this PR #11 and  PR #9 

after fix

image

### CODE REVIEW

**Comment by christianfds** [comment]
Nice one! Thank you @Karthik-PM

**Comment by christianfds** [comment]
@Karthik-PM Can you please just delete the file `out/Cross Epoch - Capitulo #1.pdf`?

**Comment by Karthik-PM** [comment]
> @Karthik-PM Can you please just delete the file `out/Cross Epoch - Capitulo #1.pdf`?

oh yes sorry about that @christianfds

**Comment by Karthik-PM** [comment]
i have added the changes @christianfds

**Comment by christianfds** [comment]
Sorry @Karthik-PM forgot to mention before.
I believe we can improve this with the following changes:
- [ ] Bring the `parse_chapter_selection` inside the while. Since there can be multiple chapters selected.
- [ ] Instead of `response not in chapters` we want it to loop while there is any issue, even considering issues from the parse.
- [ ] Trim the response so you can compare it with only an empty response.

**Comment by Alig1493** [comment]
We'd also like to check it for any whitespaces not just a single space or a new line.

**Comment by Karthik-PM** [comment]
thank you @Alig1493  @christianfds  i will add the following changes

**Comment by Karthik-PM** [comment]
@christianfds so is it like after the index of the manga is downloaded i should still be in the loop and ask whether i need to download more chapters , if not i should press a special key and then exit the loop

**Comment by Karthik-PM** [comment]
> 

yeah, you are right ! i will make that change

**Comment by christianfds** [comment]
> @christianfds so is it like after the index of the manga is downloaded i should still be in the loop and ask whether i need to download more chapters , if not i should press a special key and then exit the loop

@Karthik-PM That not need, since its possible to download multiple ranges using a single selection.

**Comment by christianfds** [comment]
Stale

**Pull request closed without merging**
